Fixed incorrect use of long timer to yield to executor, fixed crash caused by stack size being too small:
panicked at /home/user/.cargo/git/checkouts/embassy-0012190963c274d8/3b185bf/embassy-net/src/lib.rs:395:27:
RefCell already borrowed